### ISSUE TITLE
.

### ISSUE THREAD

**Issue by webproject1231111** [davidjoseph9/NexonGameSecurity-Bypass#3]
.

**Comment by davidjoseph9** [comment]
Hello, please ensure you have the latest changes merged today. There were changes made to evade detection of sig scans both for the bypass and DLLs injected after the bypass is successfully installed.

**Comment by davidjoseph9** [comment]
Sig scans lead to your account being banned. The NtReadVirtualMemory hook now checks to see if the memory is reading from a module and will check if it's in a static list of modules captured at the start.

**Comment by davidjoseph9** [comment]
As a result, it no longer needs to be packed to evade detection
